name: CI

description: Continuous Integration Workflow python projects using UV.

permissions:
  contents: write

on:
  workflow_call:
    secrets:
      github-token:
        description: "GitHub token for tagging and releases"
        required: true
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.12"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare UV Environment
        uses: qubone/q-python-ci-actions/.github/actions/prepare-uv-environment@main
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          dependency-groups: "lint"
      - name: Run Lint
        uses: qubone/q-python-ci-actions/.github/actions/run-lint@main

  typecheck:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare UV Environment
        uses: qubone/q-python-ci-actions/.github/actions/prepare-uv-environment@main
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          dependency-groups: "typecheck"
      - name: Run Type Check
        uses: qubone/q-python-ci-actions/.github/actions/run-typecheck@main

  test:
    needs: typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare UV Environment
        uses: qubone/q-python-ci-actions/.github/actions/prepare-uv-environment@main
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          dependency-groups: "test"
      - name: Run Tests
        uses: qubone/q-python-ci-actions/.github/actions/run-tests@main

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare UV Environment
        uses: qubone/q-python-ci-actions/.github/actions/prepare-uv-environment@main
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Run Build
        uses: qubone/q-python-ci-actions/.github/actions/run-build@main
  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare UV Environment
        uses: qubone/q-python-ci-actions/.github/actions/prepare-uv-environment@main
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Bump Patch and Tag
        id: bump
        uses: qubone/q-python-ci-actions/.github/actions/bump-patch-and-tag@main
        with:
          github-token: ${{ secrets.github-token }}
          dry-run: ${{ github.event_name == 'pull_request' }}

      - name: Create Release Notes
        id: notes
        uses: qubone/q-python-ci-actions/.github/actions/create-release-notes@main
        with:
          new-tag: ${{ steps.bump.outputs.new-tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump.outputs.new-tag }}
          name: Release ${{ steps.bump.outputs.new-tag }}
          body: ${{ steps.notes.outputs.body }}